# Generated by Django 6.0.5 on 2026-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(max_length=100, verbose_name='اسم المندوب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('order_id', models.IntegerField(verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري التوصيل'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'توصيلة',
                'verbose_name_plural': 'التوصيلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
